name: flutter_login_screen
description: Functional Flutter Starter Kit
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: 0.5.6
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  progress_dialog: ^1.2.4
  flutter_facebook_login: 3.0.0
  http: 0.12.2
  image_picker: ^0.6.7+22
  firebase_storage: ^7.0.0
  cached_network_image: ^2.5.0
  smooth_page_indicator: ^0.2.0
  animations: ^2.0.0
  percent_indicator: ^2.1.3
  flutter_svg: ^0.19.3
  fancy_bottom_navigation: ^0.3.2
  universal_platform: ^0.1.3
  flutter_rating_bar: ^4.0.0
  responsive_builder: ^0.3.0
  provider: ^5.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Sans_bold
      fonts:
        - asset: assets/fonts/Product-Sans-Bold.ttf
    - family: Sans_bold_italic
      fonts:
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Work_sans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
    - family: Work_sans_bold
      fonts:
        - asset: assets/fonts/WorkSans-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/nunito-sans.semibold.ttf
    - family: Circular
      fonts:
        - asset: assets/fonts/Circular/Circular-Std-Font.otf
         
